# Generated by Django 5.2.8 on 2025-11-17 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='running', max_length=20)),
                ('agents', models.ManyToManyField(related_name='campaigns', to='account.agent')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('cost', models.FloatField(default=0.0)),
                ('outcome', models.CharField(max_length=100)),
                ('call_duration', models.FloatField(default=0.0)),
                ('recording', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='account.campaign')),
            ],
        ),
    ]
